(function(g){var window=this;'use strict';var Qjb=function(a,b){if(!Number.isFinite(a))return String(a);a=String(a);var c=a.indexOf(".");c===-1&&(c=a.length);var d=a[0]==="-"?"-":"";d&&(a=a.substring(1));return d+(0,g.S9a)("0",Math.max(0,b-c))+a},Rjb=function(){return{I:"svg",
X:{fill:"#fff",height:"24px",viewBox:"0 0 24 24",width:"24px"},V:[{I:"path",X:{d:"M12 22c1.1 0 2-.9 2-2h-4c0 1.1.9 2 2 2zm6-6v-5c0-3.07-1.64-5.64-4.5-6.32V4c0-.83-.67-1.5-1.5-1.5s-1.5.67-1.5 1.5v.68C7.63 5.36 6 7.92 6 11v5l-2 2v1h16v-1l-2-2z"}}]}},Sjb=function(){return{I:"svg",
X:{fill:"#fff",height:"24px",viewBox:"0 0 24 24",width:"24px"},V:[{I:"path",X:{d:"M12 22c1.1 0 2-.9 2-2h-4c0 1.1.9 2 2 2zm6-6v-5c0-3.07-1.63-5.64-4.5-6.32V4c0-.83-.67-1.5-1.5-1.5s-1.5.67-1.5 1.5v.68C7.64 5.36 6 7.92 6 11v5l-2 2v1h16v-1l-2-2zm-2 1H8v-6c0-2.48 1.51-4.5 4-4.5s4 2.02 4 4.5v6z"}}]}},Ujb=function(a){typeof a==="number"?(this.date=Tjb(a,0,1),y5(this,1)):g.Qa(a)?(this.date=Tjb(a.getFullYear(),a.getMonth(),a.getDate()),y5(this,a.getDate())):(this.date=new Date(g.Va()),a=this.date.getDate(),
this.date.setHours(0),this.date.setMinutes(0),this.date.setSeconds(0),this.date.setMilliseconds(0),y5(this,a))},Tjb=function(a,b,c){b=new Date(a,b,c);
a>=0&&a<100&&b.setFullYear(b.getFullYear()-1900);return b},y5=function(a,b){a.getDate()!=b&&a.date.setUTCHours(a.date.getUTCHours()+(a.getDate()<b?1:-1))},z5=function(a,b){g.NR.call(this,a,{I:"div",
S:"ytp-reminder-menu",X:{role:"menu",tabindex:"-1"},V:[{I:"div",S:"ytp-reminder-menu-contents",V:[{I:"div",S:"ytp-reminder-menu-items"}]}]},100,!0);this.j=b;this.C=[];this.menuPopupRenderer=void 0;this.items=this.Ea("ytp-reminder-menu-items");this.hide()},Vjb=function(a){return(a.menuPopupRenderer&&a.menuPopupRenderer.items||[]).reduce(function(b,c){c&&c.menuServiceItemRenderer&&b.push(c.menuServiceItemRenderer);
return b},[])},A5=function(a){g.S.call(this,{I:"div",
V:[{I:"button",La:["ytp-offline-slate-button","ytp-button"],V:[{I:"div",S:"ytp-offline-slate-button-icon",va:"{{icon}}"},{I:"div",S:"ytp-offline-slate-button-text",va:"{{text}}"}]}]});this.J=a;this.upcomingEventReminderButtonRenderer=this.toggleButtonRenderer=null;this.B=void 0;this.D=this.j=null;(this.G=this.Ea("ytp-offline-slate-button"))&&this.T(this.G,"click",this.K);this.hide()},Xjb=function(a,b,c){!a.toggleButtonRenderer&&b&&b.toggleButtonRenderer?a.toggleButtonRenderer=b.toggleButtonRenderer:
b&&b.toggleButtonRenderer||(a.toggleButtonRenderer=null);
!a.upcomingEventReminderButtonRenderer&&c&&g.Q(c,Wjb)?a.upcomingEventReminderButtonRenderer=g.Q(c,Wjb):c&&g.Q(c,Wjb)||(a.upcomingEventReminderButtonRenderer=null);B5(a)},B5=function(a){if(a.toggleButtonRenderer){var b=a.toggleButtonRenderer;
if(b.isToggled){var c=b.toggledText?g.qx(b.toggledText):"";a.update({text:c,icon:Yjb(b.toggledIcon)})}else c=b.defaultText?g.qx(b.defaultText):"",a.update({text:c,icon:Yjb(b.defaultIcon)});a.show()}else a.upcomingEventReminderButtonRenderer?(b=Zjb(a))?(c=b.text?g.qx(b.text):"",a.update({text:c,icon:Yjb(b.icon)}),a.show()):a.hide():a.hide()},akb=function(a,b,c){a.D||(a.D=new g.bv(a.J.U().Zk));
var d={context:g.lu(a.D.config_||g.ku())};g.yw()&&(d.context.clientScreenNonce=g.yw());d.params=c;g.cv(a.D,b,d,{timeout:5E3,onSuccess:function(){a.upcomingEventReminderButtonRenderer&&a.B&&(a.upcomingEventReminderButtonRenderer.currentState=a.B,a.B=void 0)},
onError:function(){$jb(a)},
onTimeout:function(){$jb(a)}})},$jb=function(a){a.toggleButtonRenderer?(a.toggleButtonRenderer.isToggled=!a.toggleButtonRenderer.isToggled,B5(a)):a.upcomingEventReminderButtonRenderer&&(a.B=void 0,B5(a))},Yjb=function(a){if(!a)return null;
switch(a.iconType){case "NOTIFICATIONS":return Rjb();case "NOTIFICATIONS_NONE":return Sjb();case "NOTIFICATIONS_ACTIVE":return g.yx();default:return null}},Zjb=function(a){if(!a.upcomingEventReminderButtonRenderer)return null;
var b=a.B||a.upcomingEventReminderButtonRenderer.currentState;a=g.w(a.upcomingEventReminderButtonRenderer.states||[]);for(var c=a.next();!c.done;c=a.next())if((c=g.Q(c.value,bkb))&&c.state===b&&c.button&&g.Q(c.button,g.oI))return g.Q(c.button,g.oI);return null},ckb=function(a){g.S.call(this,{I:"div",
S:"ytp-offline-slate",V:[{I:"div",S:"ytp-offline-slate-background"},{I:"div",S:"ytp-offline-slate-bar",V:[{I:"span",S:"ytp-offline-slate-icon",V:[{I:"svg",X:{fill:"#fff",height:"100%",viewBox:"0 0 24 24",width:"100%"},V:[{I:"path",X:{d:"M16.94 6.91l-1.41 1.45c.9.94 1.46 2.22 1.46 3.64s-.56 2.71-1.46 3.64l1.41 1.45c1.27-1.31 2.05-3.11 2.05-5.09s-.78-3.79-2.05-5.09zM19.77 4l-1.41 1.45C19.98 7.13 21 9.44 21 12.01c0 2.57-1.01 4.88-2.64 6.54l1.4 1.45c2.01-2.04 3.24-4.87 3.24-7.99 0-3.13-1.23-5.96-3.23-8.01zM7.06 6.91c-1.27 1.3-2.05 3.1-2.05 5.09s.78 3.79 2.05 5.09l1.41-1.45c-.9-.94-1.46-2.22-1.46-3.64s.56-2.71 1.46-3.64L7.06 6.91zM5.64 5.45L4.24 4C2.23 6.04 1 8.87 1 11.99c0 3.13 1.23 5.96 3.23 8.01l1.41-1.45C4.02 16.87 3 14.56 3 11.99s1.01-4.88 2.64-6.54z"}},
{I:"circle",X:{cx:"12",cy:"12",r:"3"}}]}]},{I:"span",S:"ytp-offline-slate-messages",V:[{I:"div",S:"ytp-offline-slate-main-text",X:{"aria-label":"{{label}}"},va:"{{mainText}}"},{I:"div",S:"ytp-offline-slate-subtitle-text",va:"{{subtitleText}}"}]},{I:"span",S:"ytp-offline-slate-buttons"}]},{I:"button",La:["ytp-offline-slate-close-button","ytp-button"],V:[g.ux()]},{I:"button",La:["ytp-offline-slate-open-button","ytp-button"],V:[g.tx()]}]});var b=this;this.api=a;this.j=this.B=null;this.background=this.Ea("ytp-offline-slate-background");
this.C=this.Ea("ytp-offline-slate-bar");this.G=new g.Xo(function(){g.ep(b.C,"ytp-offline-slate-bar-fade")},15E3);
this.K=!1;this.D=new g.Xo(function(){g.ep(b.element,"ytp-offline-slate-collapsed")},15E3);
g.P(this,this.D);g.P(this,this.G);this.countdownTimer=new g.Xo(this.Q3,1E3,this);this.T(a,"presentingplayerstatechange",this.V3);this.T(a,"livestatedata",this.Sa);a=this.Ea("ytp-offline-slate-close-button");this.T(a,"click",function(){g.ep(b.element,"ytp-offline-slate-collapsed")});
a=this.Ea("ytp-offline-slate-open-button");this.T(a,"click",function(){g.gp(b.element,"ytp-offline-slate-collapsed")});
this.hide();a=this.getVideoData();a.getPlayerResponse()&&(a=a.getPlayerResponse().playabilityStatus)&&this.Sa(a);a=this.api.getPresentingPlayerType()===8&&!this.getVideoData().ym;var c=this.api.getPresentingPlayerType()===8;g.ip(this.element,"ytp-offline-slate-premiere-trailer",a);g.ip(this.element,"ytp-offline-slate-hide-background",c)},dkb=function(a,b,c){if(b){var d=b.subtitleText!=null?g.qx(b.subtitleText):"";
c=c?c:b.mainText!=null?g.qx(b.mainText):"";var e,f,h,l;b=(l=(e=b.mainText)==null?void 0:(f=e.accessibility)==null?void 0:(h=f.accessibilityData)==null?void 0:h.label)!=null?l:c;a.update({mainText:c,subtitleText:d,label:b});g.ip(a.element,"ytp-offline-slate-single-text-line",!d);g.ip(a.C,"ytp-offline-slate-bar-hidden",!c&&!d)}},C5=function(a,b){var c=(0,g.Bt)();
this.module="heartbeat";this.trigger=a;this.j=b;this.C=c},jkb=function(a){g.SX.call(this,a);
var b=this;this.N=!1;this.Z=0;this.G=!1;this.B=new g.Xo(function(){ekb(b)},0);
this.j=this.heartbeatParams=null;this.D=!1;this.K=new g.di(1E3,6E4,1);this.sequenceNumber=0;this.offlineSlate=null;this.oa=new g.bv(void 0);this.attestationResponse=Promise.resolve(void 0);this.Y=Promise.resolve(void 0);this.utcOffsetMinutes=-(new Ujb).getTimezoneOffset();this.C=new g.zE(this);g.P(this,this.B);g.P(this,this.C);fkb(this);gkb(this);this.C.T(a,"heartbeatparams",this.IG);this.C.T(a,"presentingplayerstatechange",this.l5);this.C.T(a,"videoplayerreset",this.m5);this.C.T(a,g.bD("heartbeat"),
this.onCueRangeEnter);this.D&&this.j&&hkb(this,void 0,this.j);var c=new g.$C(1E3,0x7ffffffffffff,{priority:1,namespace:"heartbeat"}),d=new g.$C(0x8000000000000,0x8000000000000,{id:"stream_end",priority:1,namespace:"heartbeat"});a.jf([c,d]);ikb(this)},ikb=function(a){var b=a.getVideoData();
!b.L("use_rta_only_for_player")&&b.ql&&(b=b.botguardData)&&g.ZK(b,a.player.U())},kkb=function(a){var b,c;
return g.J(function(d){if(d.j==1)return g.F(d,g.zua(),2);if(!d.B)return a.sequenceNumber>=3?d.return({error:"ATTESTATION_ERROR_VM_INTERNAL_ERROR"}):d.return(void 0);b=a.getVideoData();c={};return d.return(g.yua((c.cpn=b.clientPlaybackNonce,c.encryptedVideoId=b.videoId||"",c),1500))})},fkb=function(a){var b=a.getVideoData();
if(b.ql)if(b.L("use_rta_for_player_hb"))a.attestationResponse=kkb(a);else if(b=new g.bCa(b),g.WK.isInitialized()||a.sequenceNumber>=3){var c=Promise,d=c.resolve,e=null;if(b.videoData.Cr){var f=g.cCa(b);if(f){e={};var h={};f=f.split("&");f=g.w(f);for(var l=f.next();!l.done;l=f.next())l=l.value.split("="),l.length===2&&(h[l[0]]=l[1]);h.r1a&&(e.webResponse=h.r1a);h.r1c&&(e.error=lkb[Number(h.r1c)]);e.challenge=b.videoData.Cr}}a.attestationResponse=d.call(c,e||void 0)}},mkb=function(a){var b=a.getVideoData();
if(!g.CQ(a.getVideoData())||b.ZU)return!1;if(b.useInnertubeDrmService()&&b.G){a=b.G.flavor==="playready"&&b.L("html5_innertube_heartbeats_for_playready");var c=b.G.flavor==="widevine"&&b.L("html5_innertube_heartbeats_for_widevine");b=g.YN(b.G)&&b.L("html5_innertube_heartbeats_for_fairplay");return!(a||c||b)}return!0},nkb=function(a){if(mkb(a))return!!a.heartbeatParams;
var b=a.getVideoData();return g.CQ(a.getVideoData())&&b.useInnertubeDrmService()&&!b.jl&&!b.gE?!1:!!b.heartbeatToken},D5=function(a,b){if(!a.B.isActive()&&a.N){var c=a.getVideoData();
if(nkb(a)||c.isLivePlayback){if(b===void 0)if(a.G)if(a.D)b=7500;else{var d;b=((d=a.heartbeatParams)==null?0:d.interval)?a.heartbeatParams.interval*1E3:a.getVideoData().u4||6E4}else b=1E3;a.B.start(b)}}},rkb=function(a,b,c){b.Jn&&(c=g.Pi(c,{internalipoverride:b.Jn}));
var d={cpn:b.clientPlaybackNonce};b.contextParams&&(d.context_params=b.contextParams);b.Jb&&(d.kpt=b.Jb);c=g.Pi(c,d);g.wr(c,{format:"RAW",method:"GET",timeout:3E4,onSuccess:function(e){if(!a.B.isActive()&&E5(a)){a.K.reset();a.sequenceNumber++;e=e.responseText;var f=okb(e);if(f){a.player.ib("onHeartbeat",f);var h=f.status==="ok"?f.stop_heartbeat?2:0:f.status==="stop"?1:f.status==="live_stream_offline"?0:-1}else h=(h=e.match(pkb))?h[1]==="0"?0:1:-1;qkb(a,void 0,f,e,h)}},
onError:function(e){E5(a)&&F5(a,!0,"net-"+e.status)},
onTimeout:function(){E5(a)&&F5(a,!0,"timeout")},
withCredentials:!0})},ekb=function(a){var b,c;
g.J(function(d){b=a.player.U();c=a.getVideoData();if(!E5(a))return d.return();if(mkb(a))return skb(a,b,c),d.Ga(0);fkb(a);return g.F(d,tkb(a,b,c),0)})},skb=function(a,b,c){var d;
if((d=a.heartbeatParams)!=null&&d.url){var e=g.Pi(a.heartbeatParams.url,{request_id:g.Fqa()});c.qa&&(e=g.Pi(e,{vvt:c.qa}),c.mdxEnvironment&&(e=g.Pi(e,{mdx_environment:c.mdxEnvironment})));g.lP(b,c.oauthToken).then(function(f){f&&(e=g.Pi(e,{access_token:f}));rkb(a,c,e)})}},E5=function(a){var b=a.getVideoData();
return a.player.getPresentingPlayerType()===3||g.T(a.player.getPlayerStateObject(a.getPlayerType()),4)?!1:nkb(a)||b.isLivePlayback?!0:(G5(a),!1)},tkb=function(a,b,c){var d,e,f,h,l,m,n,p,q,r,t,u,y,A,C,G,H,N,M,X;
return g.J(function(V){if(V.j==1)return d="player/heartbeat",f={videoId:c.videoId,sequenceNumber:a.sequenceNumber,heartbeatServerData:(e=a.qa)!=null?e:c.heartbeatServerData},a.Y=a.attestationResponse,c.ql?g.F(V,a.Y,3):V.Ga(2);V.j!=2&&(f.attestationResponse=V.B);h=g.eR(c);m=(l=h.client)!=null?l:{};m.utcOffsetMinutes=a.utcOffsetMinutes;f.context=h;f.cpn=c.clientPlaybackNonce;if(n=typeof Intl!=="undefined"?(new Intl.DateTimeFormat).resolvedOptions().timeZone:null)m.timeZone=n;p={heartbeatChecks:[]};
if(q=c.getPlayerResponse())c.heartbeatToken&&(f.heartbeatToken=c.heartbeatToken),(r=q.playabilityStatus)&&(t=r.liveStreamability)&&t.liveStreamabilityRenderer&&p.heartbeatChecks.push("HEARTBEAT_CHECK_TYPE_LIVE_STREAM_STATUS");c.heartbeatToken&&p.heartbeatChecks.push("HEARTBEAT_CHECK_TYPE_YPC");g.vC(b)&&(p.heartbeatChecks.push("HEARTBEAT_CHECK_TYPE_UNPLUGGED"),u=ukb(a),y={},u!==null&&(y.clientPlayerPositionUtcMillis=u),C=(A=a.player.Ab())==null?void 0:g.eY(A),H=((G=C)==null?void 0:G.freePreviewWatchedDuration)||
0,H>0&&(y.freePreviewWatchedDuration={seconds:""+H}),p.unpluggedParams=y);f.heartbeatRequestParams=p;c.isLivePlayback?(N=ukb(a),N!==null&&(f.playbackState||(f.playbackState={}),f.playbackState.playbackPosition={utcTimeMillis:N})):b.L("enable_heartbeat_vod_playback_position")&&(M=vkb(a),M!==null&&(f.playbackState||(f.playbackState={}),f.playbackState.playbackPosition={streamTimeMillis:M}));a.player.publish("heartbeatRequest",f);X={timeout:3E4,onSuccess:function(fa){if(!a.B.isActive()&&E5(a)){var pa=
a.getVideoData(),Z=pa.ql&&a.Y==null,R;pa.ql=!((R=fa.heartbeatAttestationConfig)==null||!R.requiresAttestation)||Z;Z=fa.playabilityStatus;R=JSON.stringify(Z)||"{}";fa.authenticationMismatch&&a.player.ma("authshear",{});var W=-1;var v=fa.playabilityStatus;v&&(a.player.ib("onHeartbeat",v),v.status==="OK"?W=fa.stopHeartbeat?2:0:v.status==="UNPLAYABLE"?W=1:v.status==="LIVE_STREAM_OFFLINE"&&(W=0));a.sequenceNumber&&W===-1||a.K.reset();a.sequenceNumber++;fa.heartbeatServerData&&(a.qa=fa.heartbeatServerData);
pa.jE=fa;(v=fa.playerCueRangeSet)&&g.bQ(pa,v);fa.playerCueRanges&&fa.playerCueRanges.length>0&&(pa.cueRanges=fa.playerCueRanges);var U,cb;((U=fa.progressBarConfig)==null?0:U.progressBarStartPosition)&&((cb=fa.progressBarConfig)==null?0:cb.progressBarEndPosition)&&(pa.progressBarStartPosition=fa.progressBarConfig.progressBarStartPosition,pa.progressBarEndPosition=fa.progressBarConfig.progressBarEndPosition);pa.compositeLiveIngestionOffsetToken=fa.compositeLiveIngestionOffsetToken;fa.compositeLiveStatusToken!==
pa.compositeLiveStatusToken&&(pa.compositeLiveStatusToken=fa.compositeLiveStatusToken);pa.publish("dataupdated");qkb(a,fa,Z,R,W)}},
onError:function(fa){E5(a)&&F5(a,!0,"net-"+fa.status)},
onTimeout:function(){E5(a)&&F5(a,!0,"timeout")}};
g.lP(b,g.WQ(c)).then(function(fa){fa&&(X.oX="Bearer "+fa);g.cv(a.oa,d,f,X)});
g.ua(V)})},qkb=function(a,b,c,d,e){e===-1?(c="decode "+g.Ue(d,3),F5(a,!1,c)):e===2?(G5(a),a.G=!0):(a.Z=0,a.B.stop(),e===1?(a.G=!1,c&&c.errorCode==="PLAYABILITY_ERROR_CODE_EMBARGOED"&&a.player.Zo(!0),e="pe."+(c==null?void 0:c.errorCode)+";ps."+(c==null?void 0:c.status),a.player.Of("heartbeat.stop",2,a.Xf(d),e),g.ht("heartbeatActionPlayerHalted",wkb(c)),(b==null?0:b.videoTransitionEndpoint)&&c&&(b=b.videoTransitionEndpoint,(d=g.Q(b,g.nQ))&&xkb(a,d,c,{itct:b==null?void 0:b.clickTrackingParams}))):(a.G=
!0,d=0,a.D&&c&&(d=hkb(a,b,c),a.player.publish("livestatedata",c)),d?D5(a,d):D5(a)))},hkb=function(a,b,c){var d=c.liveStreamability&&c.liveStreamability.liveStreamabilityRenderer,e=!(!d||!(d.switchStreamsImmediately||d.transitionTiming&&d.transitionTiming==="STREAM_TRANSITION_TIMING_IMMEDIATELY"));
b=ykb(a,b,d);var f=a.getVideoData(),h=a.player.getPlayerStateObject(a.getPlayerType()),l=h.isPlaying()&&!g.JQ(f)&&!a.player.isAtLiveHead(a.getPlayerType());if(f.U().yc()){var m,n=((m=a.player.He())==null?void 0:m.qc())||{};n.status=c.status||"";n.dvr=""+ +l;n["switch"]=""+ +e;n.ended=""+ +!(!d||!d.displayEndscreen);a.player.ma("heartbeat",n)}if(l&&!e)return b;e=d&&d.streamTransitionEndpoint&&g.Q(d.streamTransitionEndpoint,g.nQ);if((d&&d.transitionTiming)==="STREAM_TRANSITION_TIMING_AT_STREAM_END")a.getVideoData().transitionEndpointAtEndOfStream=
e;else if(e&&xkb(a,e,c))return b;if(c.status.toUpperCase()==="OK"){e=d&&d.broadcastId;m=a.j&&a.j.liveStreamability&&a.j.liveStreamability.liveStreamabilityRenderer&&a.j.liveStreamability.liveStreamabilityRenderer.broadcastId;l=e!==m&&e!=null;if(!g.GQ(f)||l){var p={video_id:f.videoId};f.dG&&(p.is_live_destination="1");a.player.L("web_player_heartbeat_request_watch_next")||(p.disable_watch_next=!0,p.raw_watch_next_response=f.getWatchNextResponse());p.autonav_state=f.autonavState;p.oauth_token=f.oauthToken;
p.force_gvi=f.In;p.Ym=f.Ym;f.K&&(p.vss_credentials_token=f.K,p.vss_credentials_token_type=f.Cn);f.qa&&(p.vvt=f.qa);d=void 0;g.GQ(f)?l&&(d=new C5("broadcastIdChanged",m+","+e),a.cL("HEARTBEAT_ACTION_TRIGGER_IMMEDIATE","HEARTBEAT_ACTION_TRANSITION_REASON_BROADCAST_ID_CHANGED",c)):(e&&(d=new C5("formatsReceived",""+e)),a.cL("HEARTBEAT_ACTION_TRIGGER_IMMEDIATE","HEARTBEAT_ACTION_TRANSITION_REASON_LIVE_STREAM_WENT_ONLINE",c));a.player.loadVideoByPlayerVars(p,void 0,void 0,void 0,d);return b}a.player.Dg("heartbeat",
a.getPlayerType())}d&&d.displayEndscreen&&(a.offlineSlate?(a=a.offlineSlate,a.K=!0,a.Fb&&a.api.yC()):h.isBuffering()&&(f=((p=a.player.He())==null?void 0:p.qc())||{},a.player.ma("hbse",f,!0),a.player.yC(),a.player.ib("onLiveMediaEnded",c)));return b},ykb=function(a,b,c){return a.player.L("web_player_use_heartbeat_poll_delay_ms")&&(a=Number(b==null?void 0:b.pollDelayMs))?a:(c=Number(c==null?void 0:c.pollDelayMs))?c:0},F5=function(a,b,c){var d=a.player.U();
if(!a.B.isActive()){a.B.stop();a.Z++;var e=b?"heartbeat.net":"heartbeat.servererror";var f=a.getVideoData();if(f.XU||b&&!g.CQ(a.getVideoData())&&!nkb(a)&&f.isLivePlayback)f=!1;else{var h,l;((l=a.heartbeatParams)==null?0:l.retries)?h=a.heartbeatParams.retries:h=f.WU||5;f=a.Z>=h}f?(g.ht("heartbeatActionPlayerHalted",b?{enforcedPolicyToHaltOnNetworkFailure:!0}:wkb()),(b=a.getVideoData())&&b.isLivePlayback?a.player.Of(e,1,"\ub3d9\uc601\uc0c1 \uc7ac\uc0dd\uc774 \uc911\ub2e8\ub418\uc5c8\uc2b5\ub2c8\ub2e4. \ub2e4\uc2dc \uc2dc\ub3c4\ud574 \uc8fc\uc138\uc694.",
c):a.player.Of(e,1,"\ub3d9\uc601\uc0c1\uc5d0 \ub77c\uc774\uc120\uc2a4\ub97c \ubd80\uc5ec\ud558\ub294 \uc911\uc5d0 \uc624\ub958\uac00 \ubc1c\uc0dd\ud588\uc2b5\ub2c8\ub2e4.",c)):(d.L("html5_report_non_fatal_heartbeat_error")&&a.player.Qs(e,{msg:c}),D5(a,a.K.getValue()),g.ei(a.K))}},wkb=function(a){var b={enforcedPolicyToHaltOnNetworkFailure:!1};
a&&(b.serializedServerContext=a.additionalLoggingData);return b},G5=function(a){a.Z=0;
a.B.stop();a.G=!1;a.sequenceNumber=0},gkb=function(a){var b=a.getVideoData(),c=a.player.U();
if(b.isLivePlayback)if(g.nO(c.G)){a.D=!0;a.N=!0;if(!g.xC(c)||g.vC(c))a.offlineSlate=new ckb(a.player),g.P(a,a.offlineSlate),g.HR(a.player,a.offlineSlate.element,4);(b=b.getPlayerResponse())&&b.playabilityStatus&&(a.j=b.playabilityStatus);var d;((d=a.j)==null?void 0:d.status)!=="UNPLAYABLE"&&(a.j?(d=ykb(a,void 0,a.j.liveStreamability&&a.j.liveStreamability.liveStreamabilityRenderer))?D5(a,d):D5(a,7500):D5(a,1E3))}else a.player.Of("html5.unsupportedlive",2,"HTML5_NO_AVAILABLE_FORMATS_FALLBACK","nolive.1");
else g.Sb(b.Da,"heartbeat")&&a.player.Dg("heartbeat",a.getPlayerType())},xkb=function(a,b,c,d){var e=b&&b.videoId;
return e?(a.player.xp(e,Object.assign({},{autonav:"1"},d||{}),void 0,!0,!0,b,g.WQ(a.getVideoData())),a.cL("HEARTBEAT_ACTION_TRIGGER_IMMEDIATE","HEARTBEAT_ACTION_TRANSITION_REASON_HAS_NEW_STREAM_TRANSITION_ENDPOINT",c),!0):!1},ukb=function(a){return(a=a.player.getProgressState(a.getPlayerType()).ingestionTime)&&isFinite(a)?""+Math.floor(a*1E3):null},vkb=function(a){return(a=a.player.getCurrentTime(a.getPlayerType()))&&isFinite(a)?""+Math.floor(a*1E3):null},okb=function(a){try{var b=JSON.parse(a);
return b!=null?b:void 0}catch(c){}},zkb={ERAS:["BC",
"AD"],ERANAMES:["Before Christ","Anno Domini"],NARROWMONTHS:"JFMAMJJASOND".split(""),STANDALONENARROWMONTHS:"JFMAMJJASOND".split(""),MONTHS:"January February March April May June July August September October November December".split(" "),STANDALONEMONTHS:"January February March April May June July August September October November December".split(" "),SHORTMONTHS:"Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec".split(" "),STANDALONESHORTMONTHS:"Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec".split(" "),
WEEKDAYS:"Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),STANDALONEWEEKDAYS:"Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),SHORTWEEKDAYS:"Sun Mon Tue Wed Thu Fri Sat".split(" "),STANDALONESHORTWEEKDAYS:"Sun Mon Tue Wed Thu Fri Sat".split(" "),NARROWWEEKDAYS:"SMTWTFS".split(""),STANDALONENARROWWEEKDAYS:"SMTWTFS".split(""),SHORTQUARTERS:["Q1","Q2","Q3","Q4"],QUARTERS:["1st quarter","2nd quarter","3rd quarter","4th quarter"],AMPMS:["AM","PM"],DATEFORMATS:["EEEE, MMMM d, y",
"MMMM d, y","MMM d, y","M/d/yy"],TIMEFORMATS:["h:mm:ss\u202fa zzzz","h:mm:ss\u202fa z","h:mm:ss\u202fa","h:mm\u202fa"],DATETIMEFORMATS:["{1} 'at' {0}","{1} 'at' {0}","{1}, {0}","{1}, {0}"],FIRSTDAYOFWEEK:6,WEEKENDRANGE:[5,6],FIRSTWEEKCUTOFFDAY:5};
zkb={ERAS:["BC","AD"],ERANAMES:["\uae30\uc6d0\uc804","\uc11c\uae30"],NARROWMONTHS:"1\uc6d4 2\uc6d4 3\uc6d4 4\uc6d4 5\uc6d4 6\uc6d4 7\uc6d4 8\uc6d4 9\uc6d4 10\uc6d4 11\uc6d4 12\uc6d4".split(" "),STANDALONENARROWMONTHS:"1\uc6d4 2\uc6d4 3\uc6d4 4\uc6d4 5\uc6d4 6\uc6d4 7\uc6d4 8\uc6d4 9\uc6d4 10\uc6d4 11\uc6d4 12\uc6d4".split(" "),MONTHS:"1\uc6d4 2\uc6d4 3\uc6d4 4\uc6d4 5\uc6d4 6\uc6d4 7\uc6d4 8\uc6d4 9\uc6d4 10\uc6d4 11\uc6d4 12\uc6d4".split(" "),STANDALONEMONTHS:"1\uc6d4 2\uc6d4 3\uc6d4 4\uc6d4 5\uc6d4 6\uc6d4 7\uc6d4 8\uc6d4 9\uc6d4 10\uc6d4 11\uc6d4 12\uc6d4".split(" "),
SHORTMONTHS:"1\uc6d4 2\uc6d4 3\uc6d4 4\uc6d4 5\uc6d4 6\uc6d4 7\uc6d4 8\uc6d4 9\uc6d4 10\uc6d4 11\uc6d4 12\uc6d4".split(" "),STANDALONESHORTMONTHS:"1\uc6d4 2\uc6d4 3\uc6d4 4\uc6d4 5\uc6d4 6\uc6d4 7\uc6d4 8\uc6d4 9\uc6d4 10\uc6d4 11\uc6d4 12\uc6d4".split(" "),WEEKDAYS:"\uc77c\uc694\uc77c \uc6d4\uc694\uc77c \ud654\uc694\uc77c \uc218\uc694\uc77c \ubaa9\uc694\uc77c \uae08\uc694\uc77c \ud1a0\uc694\uc77c".split(" "),STANDALONEWEEKDAYS:"\uc77c\uc694\uc77c \uc6d4\uc694\uc77c \ud654\uc694\uc77c \uc218\uc694\uc77c \ubaa9\uc694\uc77c \uae08\uc694\uc77c \ud1a0\uc694\uc77c".split(" "),
SHORTWEEKDAYS:"\uc77c\uc6d4\ud654\uc218\ubaa9\uae08\ud1a0".split(""),STANDALONESHORTWEEKDAYS:"\uc77c\uc6d4\ud654\uc218\ubaa9\uae08\ud1a0".split(""),NARROWWEEKDAYS:"\uc77c\uc6d4\ud654\uc218\ubaa9\uae08\ud1a0".split(""),STANDALONENARROWWEEKDAYS:"\uc77c\uc6d4\ud654\uc218\ubaa9\uae08\ud1a0".split(""),SHORTQUARTERS:["1\ubd84\uae30","2\ubd84\uae30","3\ubd84\uae30","4\ubd84\uae30"],QUARTERS:["\uc81c 1/4\ubd84\uae30","\uc81c 2/4\ubd84\uae30","\uc81c 3/4\ubd84\uae30","\uc81c 4/4\ubd84\uae30"],AMPMS:["\uc624\uc804",
"\uc624\ud6c4"],DATEFORMATS:["y\ub144 MMMM d\uc77c EEEE","y\ub144 MMMM d\uc77c","y. M. d.","yy. M. d."],TIMEFORMATS:["a h\uc2dc m\ubd84 s\ucd08 zzzz","a h\uc2dc m\ubd84 s\ucd08 z","a h:mm:ss","a h:mm"],DATETIMEFORMATS:["{1} {0}","{1} {0}","{1} {0}","{1} {0}"],FIRSTDAYOFWEEK:6,WEEKENDRANGE:[5,6],FIRSTWEEKCUTOFFDAY:5};var lkb=["ATTESTATION_ERROR_UNKNOWN","ATTESTATION_ERROR_VM_NOT_INITIALIZED","ATTESTATION_ERROR_VM_NO_RESPONSE","ATTESTATION_ERROR_VM_TIMEOUT","ATTESTATION_ERROR_VM_INTERNAL_ERROR"];
g.k=Ujb.prototype;g.k.tY=zkb.FIRSTDAYOFWEEK;g.k.uY=zkb.FIRSTWEEKCUTOFFDAY;g.k.clone=function(){var a=new Ujb(this.date);a.tY=this.tY;a.uY=this.uY;return a};
g.k.getFullYear=function(){return this.date.getFullYear()};
g.k.getYear=function(){return this.getFullYear()};
g.k.getMonth=function(){return this.date.getMonth()};
g.k.getDate=function(){return this.date.getDate()};
g.k.getTime=function(){return this.date.getTime()};
g.k.getDay=function(){return this.date.getDay()};
g.k.getUTCFullYear=function(){return this.date.getUTCFullYear()};
g.k.getUTCMonth=function(){return this.date.getUTCMonth()};
g.k.getUTCDate=function(){return this.date.getUTCDate()};
g.k.getUTCDay=function(){return this.date.getDay()};
g.k.getUTCHours=function(){return this.date.getUTCHours()};
g.k.getUTCMinutes=function(){return this.date.getUTCMinutes()};
g.k.getTimezoneOffset=function(){return this.date.getTimezoneOffset()};
g.k.set=function(a){this.date=new Date(a.getFullYear(),a.getMonth(),a.getDate())};
g.k.setFullYear=function(a){this.date.setFullYear(a)};
g.k.setYear=function(a){this.setFullYear(a)};
g.k.setMonth=function(a){this.date.setMonth(a)};
g.k.setDate=function(a){this.date.setDate(a)};
g.k.setTime=function(a){this.date.setTime(a)};
g.k.setUTCFullYear=function(a){this.date.setUTCFullYear(a)};
g.k.setUTCMonth=function(a){this.date.setUTCMonth(a)};
g.k.setUTCDate=function(a){this.date.setUTCDate(a)};
g.k.add=function(a){if(a.years||a.months){var b=this.getMonth()+a.months+a.years*12,c=this.getYear()+Math.floor(b/12);b%=12;b<0&&(b+=12);a:{switch(b){case 1:var d=c%4!=0||c%100==0&&c%400!=0?28:29;break a;case 5:case 8:case 10:case 3:d=30;break a}d=31}d=Math.min(d,this.getDate());this.setDate(1);this.setFullYear(c);this.setMonth(b);this.setDate(d)}a.days&&(c=this.getYear(),b=c>=0&&c<=99?-1900:0,a=new Date((new Date(c,this.getMonth(),this.getDate(),12)).getTime()+a.days*864E5),this.setDate(1),this.setFullYear(a.getFullYear()+
b),this.setMonth(a.getMonth()),this.setDate(a.getDate()),y5(this,a.getDate()))};
g.k.toString=function(){var a=this.getFullYear(),b=a<0?"-":a>=1E4?"+":"";return[b+Qjb(Math.abs(a),b?6:4),Qjb(this.getMonth()+1,2),Qjb(this.getDate(),2)].join("")+""};
g.k.valueOf=function(){return this.date.valueOf()};var Akb=new g.xq("addUpcomingEventReminderEndpoint");var Bkb=new g.xq("removeUpcomingEventReminderEndpoint");var Ckb=new g.xq("updateUpcomingEventReminderButtonStateCommand");var Wjb=new g.xq("upcomingEventReminderButtonRenderer"),bkb=new g.xq("upcomingEventReminderButtonStateRenderer");g.z(z5,g.NR);
z5.prototype.updateMenuItems=function(){var a=this,b=Vjb(this),c=0;c=0;for(var d={};c<b.length;d={KZ:void 0},c++){var e=this.C[c];e||(e=new g.S({I:"div",S:"ytp-reminder-menu-item",X:{role:"menuitem",tabindex:"0"},V:[{I:"div",S:"ytp-reminder-menu-item-icon",va:"{{icon}}"},{I:"div",S:"ytp-reminder-menu-item-label",va:"{{text}}"}]}),d.KZ=c,e.listen("click",function(h){return function(){var l=h.KZ;a.Mb();l=Vjb(a)[l];a.publish("reminderMenuItemClicked",l.serviceEndpoint||l.command)}}(d)),e.Ia(this.items),
this.C[c]=e);
var f=b[c];d=null;switch(f.icon&&f.icon.iconType){case "NOTIFICATIONS":d=Rjb();break;case "NOTIFICATIONS_NONE":d=Sjb();break;case "NOTIFICATIONS_ACTIVE":d=g.yx()}f=f.text?g.qx(f.text):"";e.update({icon:d,text:f})}for(;c<this.C.length;)this.C.pop().dispose();c===0?this.Mb():this.md(this.j)};
z5.prototype.hide=function(){this.j&&this.j.removeAttribute("aria-haspopup");g.NR.prototype.hide.call(this)};
z5.prototype.show=function(){this.j&&this.j.setAttribute("aria-haspopup","true");g.NR.prototype.show.call(this)};
z5.prototype.xa=function(){g.ob(this.C);g.NR.prototype.xa.call(this)};g.z(A5,g.S);
A5.prototype.K=function(){if(this.toggleButtonRenderer){var a=this.toggleButtonRenderer;a.isToggled?this.C(a.toggledServiceEndpoint):this.C(a.defaultServiceEndpoint);a.isToggled=!a.isToggled;B5(this)}else if(this.upcomingEventReminderButtonRenderer)if(this.j&&this.j.Fb)this.j.Mb();else{var b=Zjb(this);b&&this.C(b.serviceEndpoint||b.command);b=((a=g.Q(b==null?void 0:b.command,g.qy))==null?void 0:a.commands)||[];a:{a=g.w(b);for(var c=a.next();!c.done;c=a.next()){var d=b=void 0;if(c=(b=g.Q(c.value,g.Nab))==
null?void 0:(d=b.popup)==null?void 0:d.menuPopupRenderer){a=c;break a}}a=void 0}this.j||(this.j=new z5(this.J,this.G),this.j.Ia(this.element),g.P(this,this.j),this.j.subscribe("reminderMenuItemClicked",this.C,this));b=this.j;b.menuPopupRenderer=a;b.updateMenuItems()}};
A5.prototype.C=function(a){var b=g.Q(a,Akb),c=g.Q(a,Bkb);if(a&&(b||c)){if(b){var d=b;var e="notification/add_upcoming_event_reminder"}else c&&(d=c,e="notification/remove_upcoming_event_reminder");if(e&&d&&d.params)for(akb(this,e,d.params),a=g.w(d.commands||[]),b=a.next();!b.done;b=a.next())if((b=b.value)&&g.Q(b,Ckb)){this.B=g.Q(b,Ckb).state;B5(this);break}}};g.z(ckb,g.S);g.k=ckb.prototype;g.k.getPlayerType=function(){if(this.api.getPresentingPlayerType()===8)return 1};
g.k.getVideoData=function(){return this.api.getVideoData(this.getPlayerType())};
g.k.Sa=function(a){var b,c,d=a==null?void 0:(b=a.liveStreamability)==null?void 0:(c=b.liveStreamabilityRenderer)==null?void 0:c.offlineSlate;if(d){this.B=a;b=d.liveStreamOfflineSlateRenderer;b.canShowCountdown?this.Q3():dkb(this,b);var e,f,h,l;if(c=a==null?void 0:(e=a.liveStreamability)==null?void 0:(f=e.liveStreamabilityRenderer)==null?void 0:(h=f.offlineSlate)==null?void 0:(l=h.liveStreamOfflineSlateRenderer)==null?void 0:l.thumbnail){e=0;f=null;h=c.thumbnails;for(l=0;l<h.length;l++)h[l].width>
e&&(e=h[l].width||0,f=h[l].url);f&&(this.background.style.backgroundImage="url("+f+")")}else this.background.style.backgroundImage="";b.actionButtons||b.reminderButton?(this.j||(this.j=new A5(this.api),this.j.Ia(this.Ea("ytp-offline-slate-buttons")),g.P(this,this.j)),Xjb(this.j,b.actionButtons&&b.actionButtons[0],b.reminderButton)):this.j&&Xjb(this.j,null,null);this.B=a}else this.B=null;this.V3()};
g.k.V3=function(a){if(this.api.getPresentingPlayerType()===8)var b=!0;else{var c=this.api.getPlayerStateObject(),d=this.getVideoData();b=d.isLivePlayback&&(c.isBuffering()||g.T(c,2)||g.T(c,64));var e=d.autonavState===2&&g.T(c,2);c=c.isPlaying()&&!g.JQ(d)&&!this.api.isAtLiveHead(void 0,!0);b=b&&!c&&!e}b&&this.B?this.Fb?(a==null?0:g.oy(a,2))&&!this.getVideoData().ym&&(g.gp(this.element,"ytp-offline-slate-collapsed"),this.D.stop(),g.gp(this.C,"ytp-offline-slate-bar-fade"),this.G.start()):(this.show(),
this.D.start(),this.api.publish("offlineslatestatechange"),this.K&&this.api.yC()):this.Fb&&(this.hide(),this.api.publish("offlineslatestatechange"))};
g.k.Q3=function(){var a,b,c,d,e=(a=this.B)==null?void 0:(b=a.liveStreamability)==null?void 0:(c=b.liveStreamabilityRenderer)==null?void 0:(d=c.offlineSlate)==null?void 0:d.liveStreamOfflineSlateRenderer;e&&(a=Math.floor(g.Va()/1E3),b=e.canShowCountdown&&Number(e.scheduledStartTime),!b||b<=a?(dkb(this,e),this.countdownTimer.stop()):(dkb(this,e,g.yy(b-a)),g.Yo(this.countdownTimer)))};
g.k.xa=function(){this.countdownTimer.dispose();this.countdownTimer=null;g.S.prototype.xa.call(this)};C5.prototype.B=function(a){return this.trigger&&a.trigger?this.module===a.module&&this.trigger===a.trigger&&this.j===a.j:!1};
C5.prototype.isExpired=function(){return(0,g.Bt)()-this.C>6E4};
C5.prototype.toString=function(){return this.module+":"+this.trigger+":"+this.j};g.z(jkb,g.SX);g.k=jkb.prototype;g.k.xa=function(){G5(this);this.player.qf("heartbeat");g.SX.prototype.xa.call(this)};
g.k.onCueRangeEnter=function(){this.N=!0;D5(this,2E3)};
g.k.IG=function(a){this.heartbeatParams=a;D5(this,2E3)};
g.k.l5=function(a){var b;this.player.getPresentingPlayerType()!==8&&((b=this.j)==null?void 0:b.status)!=="UNPLAYABLE"&&(g.T(a.state,2)||g.T(a.state,64)?(G5(this),this.D&&(this.N=!0,D5(this,1E3))):(g.T(a.state,1)||g.T(a.state,8))&&D5(this,2E3))};
g.k.m5=function(){this.player.getPresentingPlayerType()!==3&&D5(this,2E3)};
g.k.getPlayerType=function(){if(this.player.getPresentingPlayerType()===8)return 1};
g.k.getVideoData=function(){return this.player.getVideoData(this.getPlayerType())};
g.k.xn=function(a){switch(a){case 4:case 3:return!1}return!0};
g.k.cL=function(a,b,c){a={trigger:a,reason:b};c&&(a.serializedServerContext=c.additionalLoggingData);g.ht("heartbeatActionPlayerTransitioned",a)};
g.k.Xf=function(a){var b="LICENSE",c=okb(a);if(c)return c.reason||g.nY[b]||"";(a=a.match(pkb))&&(a=Number(a[1]))&&(b=g.Jwa(a));return g.nY[b]||""};
g.k.VF=function(){return!!this.offlineSlate&&this.offlineSlate.Fb};
var pkb=/^GLS\/1.0 (\d+) (\w+).*?\r\n\r\n([\S\s]*)$/;g.RX("heartbeat",jkb);})(_yt_player);
